"""Tests for binary-sensor-protocol-parser (grader)."""

import json
import os
import subprocess
import pytest

OUTPUT_FILE = "/app/output/results.json"


@pytest.fixture(scope="session")
def hidden_result_data():
    """Run the agent's parser against a hidden binary fixture and return the parsed JSON.

    The hidden binary is generated by tests/hidden_data/generate.py, which is not
    present in the Docker image (tests/ is not mounted during the agent's solve
    phase). It uses entirely different sensor IDs, timestamps, and values from the
    main fixture, so any agent that hardcodes or derives answers solely from
    /app/data/sensor_dump.bin will fail these tests.

    The hidden fixture contains 7 packets: 2 valid (temperature, humidity) and 5
    errors — two checksum_mismatch (one of which also has an unknown type byte to
    test priority ordering), one unknown_sensor_type, one payload_length_mismatch,
    and one truncated_packet — with a junk byte section between packets to verify
    the parser's scanning logic generalises to unseen input.
    """
    bin_path = "/tmp/hidden_dump.bin"
    json_path = "/tmp/hidden_results.json"

    gen = subprocess.run(
        ["python3", "/tests/hidden_data/generate.py", bin_path],
        capture_output=True, text=True,
    )
    assert gen.returncode == 0, f"Hidden binary generation failed: {gen.stderr}"

    parse = subprocess.run(
        ["python3", "/solution/parser.py", bin_path, json_path],
        capture_output=True, text=True,
    )
    assert parse.returncode == 0, f"Parser failed on hidden binary: {parse.stderr}"

    with open(json_path) as f:
        return json.load(f)



@pytest.fixture(scope="session")
def result_data():
    """Load and return the parsed JSON output produced by the solution."""
    assert os.path.isfile(OUTPUT_FILE), f"Output file not found: {OUTPUT_FILE}"
    with open(OUTPUT_FILE) as f:
        return json.load(f)


def test_output_structure(result_data):
    """Validates that results.json has the required top-level keys and correct types.

    The spec mandates a 'packets' list and a 'summary' object. Missing or
    wrong-typed fields indicate a malformed output.
    """
    assert "packets" in result_data, "'packets' key missing from output"
    assert "summary" in result_data, "'summary' key missing from output"
    assert isinstance(result_data["packets"], list)
    summary = result_data["summary"]
    for key in ("total_packets", "valid_packets", "error_packets"):
        assert key in summary, f"summary missing key: {key}"
        assert isinstance(summary[key], int), f"summary['{key}'] must be an integer"
    assert "by_sensor_type" in summary, "'by_sensor_type' missing from summary"
    assert "by_error_type" in summary, "'by_error_type' missing from summary"
    assert isinstance(summary["by_sensor_type"], dict)
    assert isinstance(summary["by_error_type"], dict)


def test_summary_counts(result_data):
    """Validates the summary counts against the known fixture composition.

    The fixture contains 20 total packets: 11 valid and 9 errors (3 checksum
    mismatches, 2 unknown sensor types, 2 payload length mismatches, 2 truncated).
    Two sections of junk bytes are embedded in the stream and must not inflate counts.
    """
    summary = result_data["summary"]
    assert summary["total_packets"] == 20
    assert summary["valid_packets"] == 11
    assert summary["error_packets"] == 9


def test_summary_consistent_with_packets(result_data):
    """Validates that summary values are arithmetically consistent with the packets list.

    Total must equal valid plus error, and each count must match what is actually
    present in the packets array so that the summary cannot be hardcoded separately.
    """
    packets = result_data["packets"]
    summary = result_data["summary"]
    valid_count = sum(1 for p in packets if p.get("status") == "ok")
    error_count = sum(1 for p in packets if p.get("status") == "error")
    assert summary["total_packets"] == len(packets)
    assert summary["valid_packets"] == valid_count
    assert summary["error_packets"] == error_count


def test_packet_index_ordering(result_data):
    """Validates that packets appear in file order with consecutive zero-based indices.

    The spec requires file-order output; out-of-order or missing indices indicate
    incorrect stream traversal.
    """
    packets = result_data["packets"]
    indices = [p["packet_index"] for p in packets]
    assert indices == list(range(len(packets))), "packet_index values must be 0-based and consecutive"


def test_temperature_packet(result_data):
    """Validates correct decoding of the first temperature packet at index 0.

    Checks sensor_id, timestamp, sensor_type string, data value (float32 round-trip),
    and unit string, all required by the protocol spec.
    """
    pkt = result_data["packets"][0]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 1
    assert pkt["timestamp"] == 1700000000
    assert pkt["sensor_type"] == "temperature"
    assert pkt["data"]["unit"] == "celsius"
    assert pkt["data"]["value"] == pytest.approx(23.5, rel=1e-5)


def test_humidity_packet(result_data):
    """Validates correct decoding of the humidity packet at index 1."""
    pkt = result_data["packets"][1]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 2
    assert pkt["timestamp"] == 1700000001
    assert pkt["sensor_type"] == "humidity"
    assert pkt["data"]["unit"] == "percent"
    assert pkt["data"]["value"] == pytest.approx(65.25, rel=1e-5)


def test_pressure_packet_after_junk(result_data):
    """Validates correct decoding of the pressure packet at index 2.

    This packet appears immediately after four junk bytes. If the parser does not
    correctly scan forward to the next magic sequence, this packet will be missed
    or shifted to a wrong index, cascading failures into all subsequent tests.
    """
    pkt = result_data["packets"][2]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 3
    assert pkt["timestamp"] == 1700000002
    assert pkt["sensor_type"] == "pressure"
    assert pkt["data"]["unit"] == "hPa"
    assert pkt["data"]["value"] == pytest.approx(1013.0, rel=1e-5)


def test_accelerometer_packet(result_data):
    """Validates correct decoding of the three-axis accelerometer packet at index 3.

    Payload is x=1.1, y=9.81, z=-0.5 as big-endian float32. Unit must be 'm/s2'.
    """
    pkt = result_data["packets"][3]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 4
    assert pkt["timestamp"] == 1700000003
    assert pkt["sensor_type"] == "accelerometer"
    assert pkt["data"]["unit"] == "m/s2"
    assert pkt["data"]["x"] == pytest.approx(1.1, rel=1e-4)
    assert pkt["data"]["y"] == pytest.approx(9.81, rel=1e-4)
    assert pkt["data"]["z"] == pytest.approx(-0.5, rel=1e-4)


def test_gyroscope_packet(result_data):
    """Validates correct decoding of the three-axis gyroscope packet at index 4.

    Payload is x=0.1, y=-0.2, z=1.57 as big-endian float32. Unit must be 'rad/s'.
    """
    pkt = result_data["packets"][4]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 5
    assert pkt["timestamp"] == 1700000004
    assert pkt["sensor_type"] == "gyroscope"
    assert pkt["data"]["unit"] == "rad/s"
    assert pkt["data"]["x"] == pytest.approx(0.1, rel=1e-4)
    assert pkt["data"]["y"] == pytest.approx(-0.2, rel=1e-4)
    assert pkt["data"]["z"] == pytest.approx(1.57, rel=1e-4)


def test_first_checksum_mismatch(result_data):
    """Validates that the corrupted-CRC temperature packet at index 5 is caught.

    The parser must verify the CRC before applying any type-specific logic and
    record the failure as 'checksum_mismatch'.
    """
    pkt = result_data["packets"][5]
    assert pkt["status"] == "error"
    assert pkt["error"] == "checksum_mismatch"


def test_unknown_sensor_type(result_data):
    """Validates that the unknown-type packet at index 6 is correctly reported.

    This packet follows the second junk section. Its CRC is valid but type byte
    0x07 is not defined. Junk-byte scanning must succeed for this to land at idx 6.
    """
    pkt = result_data["packets"][6]
    assert pkt["status"] == "error"
    assert pkt["error"] == "unknown_sensor_type"


def test_second_checksum_mismatch(result_data):
    """Validates that the second corrupted-CRC packet at index 7 is caught.

    Confirms the parser continues error detection after the previous error.
    """
    pkt = result_data["packets"][7]
    assert pkt["status"] == "error"
    assert pkt["error"] == "checksum_mismatch"


def test_first_payload_length_mismatch(result_data):
    """Validates detection of the first payload_length_mismatch at index 8.

    The packet at index 8 has sensor type 2 (pressure, expects 4 bytes) but carries
    an 8-byte payload with a valid checksum. The spec defines this as
    'payload_length_mismatch' — not 'truncated_packet' or 'checksum_mismatch'.
    This error type requires checking payload size AFTER validating the CRC and type.
    """
    pkt = result_data["packets"][8]
    assert pkt["status"] == "error"
    assert pkt["error"] == "payload_length_mismatch"


def test_mid_stream_valid_after_errors(result_data):
    """Validates that a valid temperature packet at index 9 decodes correctly.

    After four consecutive error packets (indices 5–8), normal parsing must resume.
    Sensor ID is 10, value is -10.5 degrees Celsius.
    """
    pkt = result_data["packets"][9]
    assert pkt["status"] == "ok"
    assert pkt["sensor_id"] == 10
    assert pkt["timestamp"] == 1700000009
    assert pkt["sensor_type"] == "temperature"
    assert pkt["data"]["value"] == pytest.approx(-10.5, rel=1e-4)


def test_second_payload_length_mismatch(result_data):
    """Validates detection of the second payload_length_mismatch at index 11.

    The packet at index 11 has sensor type 3 (accelerometer, expects 12 bytes) but
    carries only 8 bytes of payload with a valid checksum. It must be reported as
    'payload_length_mismatch', not as a partial accelerometer reading.
    """
    pkt = result_data["packets"][11]
    assert pkt["status"] == "error"
    assert pkt["error"] == "payload_length_mismatch"


def test_checksum_mismatch_total_count(result_data):
    """Validates that exactly three checksum_mismatch errors appear in the stream.

    The fixture has three packets with deliberately corrupted CRCs at indices 5, 7,
    and 10. Missing any one indicates incomplete CRC validation.
    """
    packets = result_data["packets"]
    count = sum(1 for p in packets if p.get("error") == "checksum_mismatch")
    assert count == 3, f"Expected 3 checksum_mismatch errors, got {count}"


def test_unknown_sensor_type_total_count(result_data):
    """Validates that exactly two unknown_sensor_type errors appear in the stream.

    Type bytes 0x07 and 0xFF are both undefined. Both must be detected despite
    having valid checksums.
    """
    packets = result_data["packets"]
    count = sum(1 for p in packets if p.get("error") == "unknown_sensor_type")
    assert count == 2, f"Expected 2 unknown_sensor_type errors, got {count}"


def test_payload_length_mismatch_total_count(result_data):
    """Validates that exactly two payload_length_mismatch errors appear in the stream.

    Indices 8 and 11 carry packets with known types and valid checksums but wrong
    payload byte counts. This error must be distinguished from truncated_packet
    (where data is missing) and from checksum_mismatch (where the CRC is wrong).
    The count must be exactly 2 — not 0 (missed) or higher (misclassified from
    other error types).
    """
    packets = result_data["packets"]
    count = sum(1 for p in packets if p.get("error") == "payload_length_mismatch")
    assert count == 2, f"Expected 2 payload_length_mismatch errors, got {count}"


def test_truncated_packet_total_count(result_data):
    """Validates that exactly two truncated_packet errors appear at end-of-stream.

    Index 18: declared body length exceeds remaining bytes.
    Index 19: magic bytes present but no pkt_len field follows.
    Both must be recorded rather than silently dropped.
    """
    packets = result_data["packets"]
    count = sum(1 for p in packets if p.get("error") == "truncated_packet")
    assert count == 2, f"Expected 2 truncated_packet errors, got {count}"


def test_trailing_truncated_packets(result_data):
    """Validates that the two trailing truncated packets land at indices 18 and 19."""
    packets = result_data["packets"]
    assert len(packets) >= 20
    assert packets[18]["status"] == "error" and packets[18]["error"] == "truncated_packet"
    assert packets[19]["status"] == "error" and packets[19]["error"] == "truncated_packet"


def test_summary_by_error_type(result_data):
    """Validates the by_error_type breakdown in the summary object.

    The spec requires a mapping from each error string to its occurrence count.
    Exact values must match the fixture: 3 checksum_mismatch, 2 unknown_sensor_type,
    2 payload_length_mismatch, 2 truncated_packet. Any missing or incorrect count
    indicates the parser is not tracking error types separately.
    """
    by_error = result_data["summary"]["by_error_type"]
    assert by_error.get("checksum_mismatch") == 3, f"checksum_mismatch: expected 3, got {by_error.get('checksum_mismatch')}"
    assert by_error.get("unknown_sensor_type") == 2, f"unknown_sensor_type: expected 2, got {by_error.get('unknown_sensor_type')}"
    assert by_error.get("payload_length_mismatch") == 2, f"payload_length_mismatch: expected 2, got {by_error.get('payload_length_mismatch')}"
    assert by_error.get("truncated_packet") == 2, f"truncated_packet: expected 2, got {by_error.get('truncated_packet')}"
    assert len(by_error) == 4, f"by_error_type must contain exactly 4 keys (omit error types with zero occurrences), got {list(by_error.keys())}"


def test_summary_by_sensor_type(result_data):
    """Validates the by_sensor_type breakdown in the summary object.

    The spec requires a mapping from each sensor type name to the count of valid
    packets of that type. The fixture produces: temperature=3, humidity=3,
    pressure=2, accelerometer=2, gyroscope=1. Any missing type or wrong count
    indicates the parser is not categorising valid packets by type.
    """
    by_sensor = result_data["summary"]["by_sensor_type"]
    assert by_sensor.get("temperature") == 3, f"temperature: expected 3, got {by_sensor.get('temperature')}"
    assert by_sensor.get("humidity") == 3, f"humidity: expected 3, got {by_sensor.get('humidity')}"
    assert by_sensor.get("pressure") == 2, f"pressure: expected 2, got {by_sensor.get('pressure')}"
    assert by_sensor.get("accelerometer") == 2, f"accelerometer: expected 2, got {by_sensor.get('accelerometer')}"
    assert by_sensor.get("gyroscope") == 1, f"gyroscope: expected 1, got {by_sensor.get('gyroscope')}"
    assert len(by_sensor) == 5, f"by_sensor_type must contain exactly 5 keys (omit types with zero valid packets), got {list(by_sensor.keys())}"


def test_hidden_summary_counts(hidden_result_data):
    """Validates correct packet counts when the parser runs on the hidden binary fixture.

    The hidden fixture has 7 packets (2 valid, 5 errors) with entirely different
    sensor IDs, timestamps, and values from the main fixture. An agent that hardcodes
    or reverse-engineers output solely from /app/data/sensor_dump.bin will produce
    wrong totals here. This test confirms the parser is a genuine general-purpose
    implementation that operates correctly on unseen binary input.
    """
    summary = hidden_result_data["summary"]
    assert summary["total_packets"] == 7, f"Expected 7 total packets in hidden fixture, got {summary['total_packets']}"
    assert summary["valid_packets"] == 2, f"Expected 2 valid packets in hidden fixture, got {summary['valid_packets']}"
    assert summary["error_packets"] == 5, f"Expected 5 error packets in hidden fixture, got {summary['error_packets']}"


def test_hidden_all_error_types(hidden_result_data):
    """Validates that all four error types are correctly detected in the hidden binary.

    The hidden fixture contains: two checksum_mismatch errors (one is a pressure packet
    with a corrupted CRC; the other has both a corrupted CRC and an unknown type byte,
    and must be classified as checksum_mismatch — not unknown_sensor_type — because
    checksum is checked before type in the priority ordering), one unknown_sensor_type,
    one payload_length_mismatch, and one truncated_packet. The hidden binary also
    includes a junk byte section between packets to test scanner generalisation.
    """
    by_error = hidden_result_data["summary"]["by_error_type"]
    assert by_error.get("checksum_mismatch") == 2, f"checksum_mismatch: expected 2, got {by_error.get('checksum_mismatch')}"
    assert by_error.get("unknown_sensor_type") == 1, f"unknown_sensor_type: expected 1, got {by_error.get('unknown_sensor_type')}"
    assert by_error.get("payload_length_mismatch") == 1, f"payload_length_mismatch: expected 1, got {by_error.get('payload_length_mismatch')}"
    assert by_error.get("truncated_packet") == 1, f"truncated_packet: expected 1, got {by_error.get('truncated_packet')}"
    assert len(by_error) == 4, f"by_error_type must have exactly 4 keys in hidden fixture, got {list(by_error.keys())}"


def test_hidden_error_priority_ordering(hidden_result_data):
    """Validates that checksum_mismatch takes priority over unknown_sensor_type.

    The hidden fixture at index 5 contains a packet with BOTH a corrupted CRC AND an
    undefined sensor type byte (0xBB). The instruction defines the priority order as:
    truncated_packet > checksum_mismatch > unknown_sensor_type > payload_length_mismatch.
    A correct parser must classify this packet as checksum_mismatch — not
    unknown_sensor_type — because checksum is checked before sensor type in the
    mandated priority order. Any implementation that checks the type before the CRC
    will produce unknown_sensor_type for this packet and fail this test.
    """
    packets = hidden_result_data["packets"]
    pkt = packets[5]
    assert pkt["status"] == "error", f"packets[5] should be an error packet, got status={pkt['status']}"
    assert pkt["error"] == "checksum_mismatch", (
        f"packets[5] has both corrupt CRC and unknown type (0xBB); "
        f"expected error='checksum_mismatch' (CRC is checked first per spec), "
        f"got error='{pkt.get('error')}'"
    )


def test_hidden_valid_packet_types(hidden_result_data):
    """Validates the valid packet sensor type breakdown for the hidden binary.

    The hidden fixture contains one valid temperature packet (sensor_id=100,
    value=15.0) and one valid humidity packet (sensor_id=104, value=80.5). No other
    sensor types produce valid packets in this binary. Correct decoding and
    categorisation of both packets is required to pass.
    """
    packets = hidden_result_data["packets"]
    by_sensor = hidden_result_data["summary"]["by_sensor_type"]
    assert by_sensor.get("temperature") == 1, f"temperature: expected 1, got {by_sensor.get('temperature')}"
    assert by_sensor.get("humidity") == 1, f"humidity: expected 1, got {by_sensor.get('humidity')}"
    assert len(by_sensor) == 2, f"by_sensor_type must have exactly 2 keys in hidden fixture, got {list(by_sensor.keys())}"
    temp_pkt = packets[0]
    assert temp_pkt["status"] == "ok"
    assert temp_pkt["sensor_id"] == 100
    assert temp_pkt["sensor_type"] == "temperature"
    assert temp_pkt["data"]["value"] == pytest.approx(15.0, rel=1e-5)


def test_output_directory_creation():
    """Validates that the parser creates the output directory if it does not already exist.

    The instruction requires: 'Create the output directory if it does not already exist.'
    This test invokes the parser with an output path whose parent directory does not
    exist prior to the call, then verifies the output file was created. A parser that
    assumes the directory already exists (e.g. by not calling os.makedirs) will raise
    a FileNotFoundError and fail this test.
    """
    out_dir = "/tmp/test_mkdir_newdir"
    out_file = f"{out_dir}/results.json"
    import shutil
    shutil.rmtree(out_dir, ignore_errors=True)
    assert not os.path.exists(out_dir), "Test setup: directory should not exist before parser runs"

    result = subprocess.run(
        ["python3", "/solution/parser.py", "/app/data/sensor_dump.bin", out_file],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, f"Parser failed: {result.stderr}"
    assert os.path.isfile(out_file), f"Output file not created at {out_file}"

    with open(out_file) as f:
        data = json.load(f)
    assert "packets" in data and "summary" in data, "Output JSON missing required keys"

    shutil.rmtree(out_dir, ignore_errors=True)

